<?php

return [
    'hours' => [
        'ontario' => [
            'Monday' => '7AM to 5PM',
            'Tuesday' => '7AM to 5PM',
            'Wednesday' => '7AM to 5PM',
            'Thursday' => '7AM to 5PM',
            'Friday' => '7AM to 5PM',
            'Saturday' => '7AM to 5PM',
            'Sunday' => '7AM to 5PM',
        ],
        'ashland' => [
            'Monday' => 'Closed',
            'Tuesday' => '9AM to 5PM',
            'Wednesday' => 'Closed',
            'Thursday' => 'Closed',
            'Friday' => '9AM to 5PM',
            'Saturday' => 'Closed',
            'Sunday' => 'Closed',
        ]
    ],

    'employees' => [
        'quals' => [
            'bsn' => 'BSN',
            'ccma' => 'CCMA',
            'cnp' => 'CNP',
            'facs' => 'FACS',
            'le' => 'LE',
            'ma' => 'MA',
            'md' => 'MD',
            'rn' => 'RN'
        ]
    ],

    'image_tags' => [
        'portrait' => 'Employee Portrait | JPG | 1080x1080px',
        'landscape' => 'Service Landscape | JPG | 1690x1080px',
        'title' => 'Service Title | JPG | 500x500px',
        'bulletin' => 'Service Bulletin | JPG | 1200x1500px',
        'ppt' => 'Pre/Post Treatment | JPG | 300x300px'
    ],

    'services' => [
        'treatments' => [
            'acne' => 'Acne',
            'acne_correction' => 'Acne Correction',
            'acne_scar_correction' => 'Acne Scar Correction',
            'adds_volume' => 'Adds Volume',
            'areola_restoration' => 'Areola Restoration',
            'aggressive_resurfacing' => 'Aggressive Resurfacing',
            'appear_fuller' => 'Appear Fuller',
            'benefits_below' => 'Benefits Below',
            'body_exfoliation' => 'Body Exfoliation',
            'brighten_skin' => 'Brighten Skin',
            'broken_capillaries' => 'Broken Capillaries',
            'brow_lift' => 'Brow Lift',
            'brown_spots' => 'Brown Spots',
            'builds_muscle' => 'Builds Muscle',
            'burns_calories' => 'Burns Calories',
            'cellular_turnover' => 'Cellular Turnover',
            'chin_definition' => 'Chin Definition',
            'chin_dimples' => 'Chin Dimples',
            'collagen_inducing' => 'Collagen Inducing',
            'customizable' => 'Customizable',
            'darker_lashes' => 'Darker Lashes',
            'dao_muscle_lift' => 'Dao Muscle Lift',
            'eyebrows' => 'Eyebrows',
            'eyelid_hooding' => 'Eyelid Hooding',
            'eyeliner' => 'Eyeliner',
            'facial_slimming' => 'Facial Slimming',
            'fades_scar_pigment' => 'Fades Scar Pigment',
            'fat_ablation' => 'Fat Ablation',
            'fat_freezing' => 'Fat Freezing',
            'fibrous_cellulite' => 'Fibrous Cellulite',
            'fine_lines' => 'Fine Lines',
            'forehead_wrinkles' => 'Forehead Wrinkles',
            'fun_with_friends' => 'Fun With Friends',
            'freckles' => 'Freckles',
            'glowing_skin' => 'Glowing Skin',
            'gummy_smile' => 'Gummy Smile',
            'hair_restoration' => 'Hair Restoration',
            'hollow_temples' => 'Hollow Temples',
            'jawline_definition' => 'Jawline Definition',
            'joint_pain' => 'Joint Pain',
            'less_stress' => 'Less Stress',
            'lifts_buttocks' => 'Lifts Buttocks',
            'lifts_skin' => 'Lifts Skin',
            'lip_color' => 'Lip Color',
            'lip_flip' => 'Lip Flip',
            'lip_volume' => 'Lip Volume',
            'liquid_nose_job' => 'Liquid Nose Job',
            'longer_lashes' => 'Longer Lashes',
            'lymphatic_drainage' => 'Lymphatic Drainage',
            'manages_anxiety' => 'Manages Anxiety',
            'marionette_lines' => 'Marionette Lines',
            'mascara_running' => 'Mascara Running',
            'metabolizes_fat' => 'Metabolizes Fat',
            'mild_exfoliation' => 'Mild Exfoliation',
            'mild_resurfacing' => 'Mild Resurfacing',
            'muscle_stimulation' => 'Muscle Stimulation',
            'nasolabial_folds' => 'Nasolabial Folds',
            'necklace_lines' => 'Necklace Lines',
            'no_lash_curlers' => 'No Lash Curlers',
            'perioral_lines' => 'Perioral Lines',
            'picture_perfect' => 'Picture Perfect',
            'pigmentation_issues' => 'Pigmentation Issues',
            'platysmal_bands' => 'Platysmal Bands',
            'pore_size' => 'Pore Size',
            'red_spots' => 'Red Spots',
            'reduces_poikiloderma' => 'Reduces Poikiloderma',
            'reduces_inflammation' => 'Reduces Inflammation',
            'reduces_lactic_acid' => 'Reduces Lactic Acid',
            'reduces_muscle_fatigue' => 'Reduces Muscle Fatigue',
            'reduces_telangiectasias' => 'Reduces Telangiectasias',
            'releases_endorphins' => 'Releases Endorphins',
            'removes_hair' => 'Removes Hair',
            'restore_cheek_volume' => 'Restore Cheek Volume',
            'restore_hand_volume' => 'Restore Hand Volume',
            'rosacea' => 'Rosacea',
            'scowl_lines' => 'Scowl Lines',
            'semi_aggressive_resurfacing' => 'Semi Aggressive Resurfacing',
            'skin_rejuvination' => 'Skin Rejuvination',
            'small_red_spots' => 'Small Red Spots',
            'stimulates_elastin' => 'Stimulates Elastin',
            'stretch_marks_and_scars' => 'Stretch Marks and Scars',
            'sun_damage' => 'Sun Damage',
            'tames_unruly_brows' => 'Tames Unruly Brows',
            'temporarily_tightens_skin' => 'Temporarily Tightens Skin',
            'tightens_skin' => 'Tightens Skin',
            'tmj' => 'TMJ',
            'undereye_hollows' => 'Undereye Hollows',
            'vascular_lesions' => 'Vascular Lesions',
            'wrinkles_around_eyes' => 'Wrinkles Around Eyes'
        ]
    ],
];
